### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by the-eric-kwok** [the-eric-kwok/my_userscripts#2]
- [x] 解决多条视频未完成且进度条位于结尾时不停跳转的问题

**Comment by nanfeng-wjg** [comment]
大佬能不能再写一个验证每天25分钟 或者插件30分后停止播放啊 求学习习惯分

**Comment by the-eric-kwok** [comment]
@nanfeng-wjg 新开一个issue噢～
我有空的时候看看怎么实现

**Comment by the-eric-kwok** [comment]
@nanfeng-wjg 已更新

**Comment by nanfeng-wjg** [comment]
> @ nanfeng-wjg已更新

感谢大佬

**Comment by the-eric-kwok** [comment]
问题已在 6cea62b5cdbc3d976b4251788efb4c030b4404ec 中修复
