### ISSUE TITLE
【U校园】无法从加密的content中解密和解析答案

### ISSUE THREAD

**Issue by junmoxiao112** [the-eric-kwok/my_userscripts#5]
大佬，能问一下你的U校园脚本unipus_helper.user.js我安装运行了之后只有一个空白窗口，你的这个脚本要怎么正确使用？
![QQ截图20211202142451](https://user-images.githubusercontent.com/95401134/144369228-05b3d826-90f0-429b-b886-1fcd40f6da91.png)

**Comment by the-eric-kwok** [comment]
你好，请把对应答题页面的url发一下，我测试一下api

**Comment by 007Hector** [comment]
我连窗口都没有

**Comment by junmoxiao112** [comment]
U校园主页https://u.unipus.cn/user/student?school_id=10530
具体课本：https://ucontent.unipus.cn/_pc_default/pc.html?cid=458190#/course-v1:Unipus+cet4_reading+2020_9/courseware/u2/u2g23/u2g24/u2g149/p_1

账号:15096615510
密码:1998918ytj


谢谢。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-eric-kwok/my_userscripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 晚上6:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-eric-kwok/my_userscripts] U校园网课答案显示 (Issue #5)





 
你好，请把对应答题页面的url发一下，我测试一下api
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by the-eric-kwok** [comment]
@junmoxiao112 我已经记录下来啦，感谢你提供的信息。为了保护你的隐私我将你的回复删除了，还望不要介意。
明天我会做进一步测试，晚安！

**Comment by the-eric-kwok** [comment]
@007Hector 在点击试题后有可能会出现脚本未能成功注入的情况，你可以尝试刷新一下页面看看是否出现窗口呢？

**Comment by the-eric-kwok** [comment]
@junmoxiao112 api返回的content是加密的，因为不知道加密方式和密钥，因此也没办法解密。
![image](https://user-images.githubusercontent.com/16463312/144533589-53d40458-e829-46a5-b06f-627fea8d0b6c.png)

**Comment by junmoxiao112** [comment]
感谢你回答我的问题，我是最近刚接触这种浏览器脚本，所以想多了解一些。我的U校园做的也差不多了，只是我的某种强迫症让我想要找到一个可用的U校园脚本。这是我这几天在B站找到的一个可用的脚本，但这个也不更新了，最新的题目它做不了，你想的话可以看一下。
[U校园答案艹.txt](https://github.com/the-eric-kwok/my_userscripts/files/7646905/U.txt)

**Comment by junmoxiao112** [comment]
谢谢你回答我的问题，我最近刚接触过这种浏览器脚本，所以想多了解一些，从油猴找到这里。这是我这几天在B站找到的一个可用的剧本，但这个也没有更新了，最新的它做不了，你想的话可以看一下。
[U校园答案艹.txt](https://github.com/the-eric-kwok/my_userscripts/files/7646919/U.txt)

**Comment by junmoxiao112** [comment]
谢谢你回答我的问题，我最近刚接触到这种浏览器脚本，所以想多了解一些，从油猴找到这里。我U校园完成的差不多了，只是某种强迫症让我想找到一个好的脚本。这是我这几天在B站找到的一个可用的脚本，但这个也没有更新了，最新的它做不了，你想的话可以看一下
[U校园答案艹.txt](https://github.com/the-eric-kwok/my_userscripts/files/7646934/U.txt)
。

**Comment by junmoxiao112** [comment]
另外在Tampermonkey中查看代码有很多未定义项，主要是”$".
![QQ截图20211203131624](https://user-images.githubusercontent.com/95401134/144549973-56174853-ce1f-44f1-bfac-
![QQ截图20211203131218](https://user-images.githubusercontent.com/95401134/144549985-68371592-07be-4873-8965-a45d9cdd6ad9.png)
3fd42a9d2380.png)
![QQ截图20211203131717](https://user-images.githubusercontent.com/95401134/144549989-cc9cc64a-f927-4a67-8162-a86bc22d1bad.png)

**Comment by junmoxiao112** [comment]
另外在Tampermonkey中查看代码有很多未定义项，主要是”$"
![QQ截图20211203131624](https://user-images.githubusercontent.com/95401134/144550093-6b760679-5960-4cd4-aee0-c71aa71df2f6.png)
![QQ截图20211203131218](https://user-images.githubusercontent.com/95401134/144550105-73aae874-50e4-4356-99e1-ee8cc2b90dde.png)
![QQ截图20211203131717](https://user-images.githubusercontent.com/95401134/144550111-6203626c-ce0d-4fe1-8875-d6ebcf929196.png)
.

**Comment by the-eric-kwok** [comment]
> 另外在Tampermonkey中查看代码有很多未定义项，主要是”$"
> 
> ![QQ截图20211203131624](https://user-images.githubusercontent.com/95401134/144550093-6b760679-5960-4cd4-aee0-c71aa71df2f6.png)
> 
> ![QQ截图20211203131218](https://user-images.githubusercontent.com/95401134/144550105-73aae874-50e4-4356-99e1-ee8cc2b90dde.png)
> 
> ![QQ截图20211203131717](https://user-images.githubusercontent.com/95401134/144550111-6203626c-ce0d-4fe1-8875-d6ebcf929196.png)
> 
> .
> 
> 

这里的 `$` 是引入的外部库 JQuery 里面的函数，Tampermonkey 的代码编辑器无法取得外部库的内容，因此会报未定义警告。

**Comment by the-eric-kwok** [comment]
> 谢谢你回答我的问题，我最近刚接触到这种浏览器脚本，所以想多了解一些，从油猴找到这里。我U校园完成的差不多了，只是某种强迫症让我想找到一个好的脚本。这是我这几天在B站找到的一个可用的脚本，但这个也没有更新了，最新的它做不了，你想的话可以看一下
> U校园答案艹.txt
> 。

感谢提供的参考脚本，解决了解密的问题，目前脚本可以使用了，我将会推送更新。可以麻烦发一下参考脚本源的网址吗？我需要确认一下对方使用的 License。十分感谢！

**Comment by the-eric-kwok** [comment]
Fixed in c50d1e86178605fe3d3b649f44092b3b417d2863

**Comment by junmoxiao112** [comment]
我这个是一个百度网盘里的，还连带浏览器。我没找到许可是在哪。这个网盘是B站UP主发的。脚本的油猴链接是已删除。
网盘链接：https://pan.baidu.com/s/1F3cBgrIhAYMdgzaKaMXhMw 
提取码：hfyt 
B站链接：https://www.bilibili.com/video/BV1oL411G781?share_source=copy_web

**Comment by the-eric-kwok** [comment]
了解了，在脚本开头有license标签，已经写明了是遵循GPLv3协议啦！新版本我已经发布了，你可以检查一下更新看看1.4版本能不能显示噢😘
这个issue我先关闭啦，如果你那边还遇到问题的话欢迎重新开启issue！

**Comment by junmoxiao112** [comment]
好的，谢谢。
