### ISSUE TITLE
【智慧树助手】自动完成弹幕答题后视频不会继续

### ISSUE THREAD

**Issue by redapple0204** [the-eric-kwok/my_userscripts#7]
RT，在脚本自动完成课程中央的弹幕答题后，视频会暂停，需要人工点击播放才可以继续播放。

**Comment by redapple0204** [comment]
另外 有时候会弹出这个错误
![image](https://user-images.githubusercontent.com/16254644/154928083-79cd3859-f5cc-4690-81ef-fad36ae6b415.png)

**Comment by the-eric-kwok** [comment]
> RT，在脚本自动完成课程中央的弹幕答题后，视频会暂停，需要人工点击播放才可以继续播放。

我这边没遇到这个问题噢，你可以检查一下你的“脚本设置”中的“暂停自动恢复播放”是否勾选了，只有勾选的情况下才会自动恢复播放。

**Comment by redapple0204** [comment]
@the-eric-kwok 看起来上述问题都是使用的扩展软件出现的问题，我换了Tampermonky后就正常了😂。

另外还想请教您一下，是否有办法让“暂停自动恢复播放”这个功能不要立即在暂停之后恢复播放？（因为有时候真的想要手动暂停一下视频）。我尝试将410行开始的``pauseDetector``函数改为async类型并且使用``await sleep();`` 也没能成功延长这个时间。

从410行开始我尝试更改的代码如下

```
async function pauseDetector() { //该行更改了函数类型
    await sleep(5000); //该行新增
    let play_Button = $(".playButton");
    if (play_Button.length > 0 && pauseResume) {
        //点击暂停按钮，将继续播放视频

        play_Button.click();
        log("继续播放");
    }
}
```

由于不是计算机专业的，抱歉麻烦您了！

**Comment by the-eric-kwok** [comment]
“暂停自动恢复播放”功能是通过一个 interval 来实现的，你可以通过搜索 `function main()` 找到对应的代码块
```javascript
    function main() {
        GM_config.init(myConfig);  //使用 myConfig 初始化 GM_config 设置面板
        init();
        window.setTimeout(oneShot, 1000);
        window.setInterval(mainLoop, (timeInterval * 1000));  // <---------- 这一行
        log("启动成功");
    }
```
通过这个定时器设置每 `timeInterval * 1000` 毫秒执行一次 `mainLoop` 函数，而对于 `pauseDetector` 函数的调用就在 `mainLoop` 中。因此如果需要增大每次执行 `mainLoop` 之间的间隔，你可以搜索变量 `timeInterval`，并增大它的值，对应的单位是“秒”。

然而对代码的改动会在脚本更新时被覆盖，因此正确的办法应该是在想要暂停的时候关闭“暂停自动恢复播放”功能。

我会在下一个版本中将循环间隔加入到“脚本设置”中，以便进行自定义。

**Comment by redapple0204** [comment]
@the-eric-kwok 明白了！十分感谢
