### ISSUE TITLE
火狐浏览器加载不出来,3月16号,也尝试改了那个.js的那个链接,换了edge正常

### ISSUE THREAD

**Issue by Qbzsq55** [the-eric-kwok/my_userscripts#8]

**Comment by the-eric-kwok** [comment]
具体是哪一个脚本呢？使用的脚本管理器是什么？请提供尽可能多的信息来帮助我定位问题，谢谢！

**Comment by Qbzsq55** [comment]
![image](https://user-images.githubusercontent.com/87004742/158579159-c31c9e84-cbe0-4a7f-b965-a23a5e79df84.png)
[Reload]智慧树考试搜题、共享课挂机刷课助手
TamperMonkey

**Comment by the-eric-kwok** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/16463312/158581088-595f6244-65c0-4a73-9cb8-239f8af10392.png">

**Comment by the-eric-kwok** [comment]
无法复现

PS：你使用的操作系统是？

**Comment by Qbzsq55** [comment]
windows

**Comment by Qbzsq55** [comment]
好像正常了

**Comment by Qbzsq55** [comment]
![image](https://user-images.githubusercontent.com/87004742/158582188-d8659dc8-ce1a-4d7b-ad9c-c14af8d282d4.png)
刚刚把那个运行时期改了一下,就正常加载了

**Comment by the-eric-kwok** [comment]
修改这个设置可能会导致其他的问题，实在要改的话我建议可以尝试改成 document-end
此外亦可尝试使用 Violentmonkey 脚本管理器代替

**Comment by Qbzsq55** [comment]
好的,好的,谢谢!
