### ISSUE TITLE
[智慧树助手]脚本已失效

### ISSUE THREAD

**Issue by ghost** [the-eric-kwok/my_userscripts#9]
**出现问题的脚本名称：**
智慧树助手

**描述问题**
脚本被检测异常

**复现步骤**
进入共享课视频界面

**屏幕截图**

![Snipaste_2022-05-12_12-03-23](https://user-images.githubusercontent.com/22217328/167990172-befe7bf7-fde9-44aa-9590-3596d946f37c.png)

**如果使用的是电脑，请填写下列信息：**
 - 操作系统：Windows
 - 浏览器：Chrome  101.0.4951.5

 - 脚本管理器：TamperMonkey V4.16

**Comment by the-eric-kwok** [comment]
目前脚本已经没有任何作用。
由于浏览器JavaScript的限制，所有通过JavaScript触发的点击事件都是不被信任的，智慧树便是通过这个方法检测是否使用了用户脚本的，此限制无法绕过，也就无法解决脚本检测的问题。
此外在考试和作业页面中，智慧树很鸡贼地将题目内容放到了一个关闭的shadow root中，JavaScript无法访问、读取题目内容，因此无法复制和查题了。此限制同样无法绕过。
如有需要可以找一下是否有配合Selenium自动化的刷课工具吧，各位再见，前程多保重！
